### ISSUE TITLE
Docs might be in the main repo

### ISSUE THREAD

**Issue by maliayas** [apache/incubator-echarts-doc#88]
IMHO, it is a best practice to put source and docs in the same repo; so that every code change and related docs change go into the same commit.

I see that in order to maintain a connection between source and docs you are using git tags in both repos. Even so, you might consider moving docs to the main repo for better peace of mind.

Moving only `en` and `zh` folders (as they are the source for docs) would be enough and this repo (incubator-echarts-doc) would contain the build code for building docs.

Thanks for the great documentation.

**Comment by Ovilia** [comment]
Thanks for your suggestion. We usually update and merge the code ASAP while it usually takes more time to write the document, as long as if it's ready before the next release. We think this makes sure the code is merged ASAP to avoid conflict.
