### ISSUE TITLE
A static build of the docs

### ISSUE THREAD

**Issue by maliayas** [apache/incubator-echarts-doc#89]
Is it possible to create a complete static/offline/portable build of the docs without requiring a web server?

I mean the exact copy of https://echarts.apache.org/en/option.html but works _completely_ offline -- even the chart examples.

**Comment by Ovilia** [comment]
I don't think we have plan for this. Because the document is keep changing and it will mislead some users if they downloaded it and never realize to update it.

**Comment by maliayas** [comment]
I see, but people who download something are already aware that it's a snapshot of the original content and must be updated __if they want__ the latest version.

The idea in this feature request has several valid points:

1. If you provide offline copy of the docs, then users would be able to store the corresponding version of the docs to the echarts version they use. Imagine that some project may use a particular old version of echarts and don't have the option to upgrade it (due to the complexity of the task). In that case, developers of that project can only browse the latest version of the docs, which may differ dramatically through years and doesn't help anymore.

2. When offline, browsing docs is impossible at the moment.

3. Currently we depend on a thirdparty server to browse echarts docs. Can anybody guarantee it will still be available 10 years from now, or 20?

If what I ask is difficult to provide, I perfectly understand. I just wanted to discuss it with you. Thanks.

**Comment by Ovilia** [comment]
Sorry for late replies.
We have no plan to provide offline document currently. If you must have it, one way to do so is to use the [option.json](https://github.com/apache/incubator-echarts-website/blob/asf-site/en/documents/option.json) locally. You can use a JSON formatter to view it more nicely.
