### ISSUE TITLE
文档书写错误

### ISSUE THREAD

**Issue by 100217** [apache/incubator-echarts-doc#97]
### Version
4.7.0

### Reproduction link
[https://echarts.apache.org/zh/option.html#tooltip.axisPointer](https://echarts.apache.org/zh/option.html#tooltip.axisPointer)

### Steps to reproduce
tooltip>>axisPointer 描述书写错误:axisPointer写成axisPinter

### What is expected?
但是使用 tooltip.axisPointer 在简单场景下会更方便一些

### What is actually happening?
但是使用 tooltip.axisPinter 在简单场景下会更方便一些

**Comment by susiwen8** [comment]
能提个 PR修正一下吗？

**Comment by plainheart** [comment]
检查了下英文文档也存在同样问题，可以在PR里一并修改下。
